---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---
## 網站資料爬取
```{r}

library(rvest)


PttMovie1<-"https://www.ptt.cc/bbs/movie/index5248.html"
PttMovie2<-"https://www.ptt.cc/bbs/movie/index5247.html"
PttMovie3<-"https://www.ptt.cc/bbs/movie/index5246.html"
PttMovie4<-"https://www.ptt.cc/bbs/movie/index5245.html"
PttMovie5<-"https://www.ptt.cc/bbs/movie/index5244.html"
a<-c(PttMovie1,PttMovie2,PttMovie3,PttMovie4,PttMovie5)

dataframeAll<-NULL  ##避免之前跑過的未清空
for(n in a){
    
        Title<-read_html(n) %>%html_nodes(".title") %>% html_text()
        PushNum<-read_html(n) %>% html_nodes(".nrec") %>% html_text()
        Author<-read_html(n) %>%html_nodes(".author") %>% html_text()
        dataframe<- data.frame(Title=Title,PushNum=PushNum,Author=Author) 
        
    dataframeAll<-rbind(dataframeAll,dataframe)
    } 



```

## 爬蟲結果呈現
```{r}

knitr::kable(dataframeAll)
```

## 解釋爬蟲結果 
```{r}
nrow(dataframeAll)
```

總共有100篇文章

```{r}
a<-table(dataframeAll$Author)
sort(a)
```
由上圖可發現，雖然"-"的數量是最多，但是"-"表示是匿名，因此不予考慮；所以文章數最多的作者分別為jay5566、kuja、zkow、jk10134。

dataframeAll這張圖表的資料是在2017/03/20從ptt電影版選出100筆最新文章統計出來的資料。從抓下的結果可以發現大多數人都在討論"美女與野獸"，其次"金剛：骷髏島"，剛好跟上週台北票房的前兩名剛好一樣(https://tw.movies.yahoo.com/chart.html?cate=taipei)，因此透過這個例子我們可以從大家發文文章標題的多寡，推論出目前正在熱映中的電影為何。